### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by woxjro** [woxjro/lazy-etherscan#1]
- [x] Display statistics about Ethereum.
- [x] Make the sidebar on the left side of the app toggleable.(1)
- [x] Add a feature equivalent to the “back” function in a web browser.(1)
- [x] Implement a help popup and navigation bar at the bottom to make the app more user-friendly.
- [x] Latest Blocks
    - [x] Display a list of the latest blocks.
    - [x] Display details of a block being focused.
- [x] Latest Transactions
    - [x] Display a list of the latest transactions.
    - [x] Display details of a transaction being focused.
    - [x] Display a list of withdrawals on the block detail screen. (1)
    - [x] In the block detail screen’s transaction list, for addresses with ENS IDs, display their IDs. (1)
    - [x] Calculate and display transaction fee values.(1)
        - https://info.etherscan.com/what-is-gas-fee/
        - `provider.fill_transaction`
    - [x] Decode and display the input data section of transactions.
        - https://github.com/miguelmota/ethereum-input-data-decoder?tab=readme-ov-file#cli 
- [x] Search Functionality
    - [x] by Address
    - [x] by Txn Hash
    - [x] by Block
    - [x] by Token (1)
    - [x] by Domain Name (1)
- [x] Documentation
- [x] Official Release
